### ISSUE TITLE
As an AI developer, I want to extract the text from detected license plates so that I can store the plate number in the database.

### ISSUE THREAD

**Issue by tanghuongcam** [BloodFutur/geicar#16]
**DoR:** 
Detected license plate images are ready for text extraction.
Text extraction algorithm is set up.

**DoD:** 
The text from the license plate is extracted (>95% accuracy).
Extracted text is saved to a database.

**Comment by Louayarfaoui95** [comment]
Issue closed due to ambigious description, refer to backlog for new tickets opened in relation with this user story.
