### ISSUE TITLE
As a parking manager, I want the vehicle to detect moving obstacles (e.g. pedestrians, moving vehicles) so that it can ensure safety in the parking lot.

### ISSUE THREAD

**Issue by tanghuongcam** [BloodFutur/geicar#22]
**DoR:**
Detection system is functional for stationary objects.

**DoD:**
The vehicle detects moving obstacles (e.g., pedestrians).
It reacts by stopping or rerouting to avoid collisions.

**Comment by BloodFutur** [comment]
It seems that issue  is #21 and #27 together.

@kekoleko123 Tell me what you think about it.

**Comment by kekoleko123** [comment]
Indeed !
