### ISSUE TITLE
[Feature] Integrate IA model training within ROS2

### ISSUE THREAD

**Issue by Louayarfaoui95** [BloodFutur/geicar#40]
Some scripts in the project already connect to the camera and publish compressed images in a topic (/image_raw.

DoR:
Some of the scripts already present should be improved to store images that are published and then allow the licence plate detection by using the trained models.

DoD:
The system identifies license plates captured in an image or video in real time using the trained models (camera connected to the car).
The result with images annotion of the detected license plates are published in a topic (/detection).

**Comment by Louayarfaoui95** [comment]
**Proposed solution:** 
You can create a node that launches an inference of the best trained model. 
You may integrate the video capture in real time in this node in order to prepare the pipeline for licence plate detection.

**Comment by Louayarfaoui95** [comment]
You may put the scripts you talked about in the description of this issue in a comment for a review and possible modifications.

**Comment by BloodFutur** [comment]
@Soso0400 The jetson works again, you can try the integration :)
