### ISSUE TITLE
[Research] Make a control flow of the car

### ISSUE THREAD

**Issue by BloodFutur** [BloodFutur/geicar#52]
The goal is to make a diagram explaining the autonomous navigation of the car. 
The diagram uses blocks and arrows.

We should show:
- localization
- trajectory control
- detection
- sensors used
- algorithms chosen

Example for a Kalman Filter:
![Image](https://github.com/user-attachments/assets/de283758-ba4d-4488-9dca-2254f5fd666c)

**Comment by kekoleko123** [comment]
Just finished the overall control flow of the car, here is the link : https://drive.google.com/file/d/1xOZl6ab0FiPloflIYl2Ouy15U6jAEtiU/view?usp=sharing

Don't hesitate to give a feedback or make some edits. The goal here is just to make the functioning clear for everyone on the project.

**Comment by emmacstn** [comment]
Good job ! Love it :)
